# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: install package...
        run: yarn install

      - name: run build...
        run: npm run build

      - name: Deploy
        run: |
          git config --global user.name tungnguyen741
          git config --global user.email tung.nguyen21098@gmail.com
          git remote set-url origin https://tungnguyen741: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@github.com/tungnguyen741/3D.git
          npm run deploy
        env:
          user_name: "tungnguyen741"
          user_email: "tung.nguyen21098@gmail.com"
          github_token: "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"
          repository: "tungnguyen741/3D.git"
